# Generated by Django 4.2.5 on 2023-09-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlili', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
