# Generated by Django 4.2.5 on 2023-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlili', '0003_choice_question_delete_time_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('time_line', models.TimeField(verbose_name='Time line')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
