# Generated by Django 4.2.5 on 2023-09-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlili', '0005_remove_program_task_remove_program_time_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='task',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='time_line',
            field=models.TimeField(default="00:00", verbose_name='time line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='time_line_end',
            field=models.TimeField(default="00:00", verbose_name='time_line_end'),
            preserve_default=False,
        ),
    ]
